from arcadepy import AsyncArcade
from dotenv import load_dotenv
from google.adk import Agent, Runner
from google.adk.artifacts import InMemoryArtifactService
from google.adk.models.lite_llm import LiteLlm
from google.adk.sessions import InMemorySessionService, Session
from google_adk_arcade.tools import get_arcade_tools
from google.genai import types
from human_in_the_loop import auth_tool, confirm_tool_usage

import os

load_dotenv(override=True)


async def main():
    app_name = "my_agent"
    user_id = os.getenv("ARCADE_USER_ID")

    session_service = InMemorySessionService()
    artifact_service = InMemoryArtifactService()
    client = AsyncArcade()

    agent_tools = await get_arcade_tools(
        client, toolkits=["Hubspot"]
    )

    for tool in agent_tools:
        await auth_tool(client, tool_name=tool.name, user_id=user_id)

    agent = Agent(
        model=LiteLlm(model=f"openai/{os.environ["OPENAI_MODEL"]}"),
        name="google_agent",
        instruction="# Introduction
Welcome to the HubSpot AI Assistant! This agent is designed to streamline your engagement processes by harnessing various tools available in the HubSpot API. Whether you need to manage deals, contacts, or communication activities, this AI agent will assist you efficiently and effectively.

# Instructions
1. **Understand the Context:** Start by identifying the specific task you want to accomplish—be it creating, updating, or retrieving information about deals, contacts, companies, activities, or users.
2. **Use Appropriate Tools:** Select and utilize the required tools based on the context of the task.
3. **Follow the Workflows:** Adhere to the defined workflows for the best results, ensuring the correct sequence of operations.
4. **Provide Clear Input:** When prompted for specific details (like IDs, names, dates, etc.), enter clear and accurate information to facilitate smooth tool operations.
5. **Handle Outputs:** Be ready to process and respond to outputs generated by the tools, whether it’s confirming an action taken, providing data retrieved, or seeking additional information if necessary.

# Workflows

## Workflow 1: Create a New Deal
1. **Tool Used:** Hubspot_GetDealPipelines
2. **Tool Used:** Hubspot_CreateDeal

## Workflow 2: Update an Existing Deal
1. **Tool Used:** Hubspot_GetDealDataByKeywords
2. **Tool Used:** Hubspot_UpdateDeal

## Workflow 3: Create a New Contact
1. **Tool Used:** Hubspot_CreateContact

## Workflow 4: Update an Existing Contact
1. **Tool Used:** Hubspot_GetContactDataByKeywords
2. **Tool Used:** Hubspot_UpdateContact

## Workflow 5: Create a Call Activity
1. **Tool Used:** Hubspot_CreateCallActivity

## Workflow 6: Create a Meeting Activity
1. **Tool Used:** Hubspot_CreateMeetingActivity

## Workflow 7: Create an Email Activity
1. **Tool Used:** Hubspot_CreateEmailActivity

## Workflow 8: Create a Note Activity
1. **Tool Used:** Hubspot_CreateNoteActivity

## Workflow 9: Search for Communications
1. **Tool Used:** Hubspot_GetCommunicationDataByKeywords

## Workflow 10: Search for Companies
1. **Tool Used:** Hubspot_GetCompanyDataByKeywords

## Workflow 11: Search for Contacts
1. **Tool Used:** Hubspot_GetContactDataByKeywords

## Workflow 12: Search for Deals
1. **Tool Used:** Hubspot_GetDealDataByKeywords

This structure will help the agent perform tasks systematically and maximize its effectiveness in managing HubSpot engagements.",
        description="An agent that uses Hubspot tools provided to perform any task",
        tools=agent_tools,
        before_tool_callback=[confirm_tool_usage],
    )

    session = await session_service.create_session(
        app_name=app_name, user_id=user_id, state={
            "user_id": user_id,
        }
    )
    runner = Runner(
        app_name=app_name,
        agent=agent,
        artifact_service=artifact_service,
        session_service=session_service,
    )

    async def run_prompt(session: Session, new_message: str):
        content = types.Content(
            role='user', parts=[types.Part.from_text(text=new_message)]
        )
        async for event in runner.run_async(
            user_id=user_id,
            session_id=session.id,
            new_message=content,
        ):
            if event.content.parts and event.content.parts[0].text:
                print(f'** {event.author}: {event.content.parts[0].text}')

    while True:
        user_input = input("User: ")
        if user_input.lower() == "exit":
            print("Goodbye!")
            break
        await run_prompt(session, user_input)


if __name__ == '__main__':
    import asyncio
    asyncio.run(main())